const descriptions = {
    "Asset": "Anything you own that has value (e.g., cash, property, stocks).",
    "Liability": "Something you owe (e.g., loans, credit card debt).",
    "Net Worth": "Your total assets minus your total liabilities.",
    "Income": "Money you earn from work, investments, or other sources.",
    "Expense": "Money you spend on goods, services, or bills.",
    "Budget": "A plan for managing income and expenses over time.",
    "Savings": "Money you set aside for future use.",
    "Interest": "The cost of borrowing money or the return on savings/investments.",
    "Compound Interest": "Interest calculated on the initial amount and also on previous interest earned.",
    "Inflation": "The rise in prices over time, reducing purchasing power.",
    "SIP (Systematic Investment Plan)": "A method of investing a fixed sum regularly in a mutual fund.",
    "NAV (Net Asset Value)": "Price of one unit of a mutual fund; changes daily.",
    "Units": "Mutual fund holdings are represented in units, bought based on NAV.",
    "Mutual Fund": "A pool of money managed by professionals to invest in various securities.",
    "AMC (Asset Management Company)": "Company that manages mutual funds.",
    "Fund Manager": "The professional who makes investment decisions for the fund.",
    "Scheme": "A specific mutual fund offering under an AMC.",
    "ROI (Return on Investment)": "The percentage return from your investments.",
    "CAGR (Compounded Annual Growth Rate)": "Average annual growth rate of investment.",
    "XIRR (Extended Internal Rate of Return)": "Used to calculate returns when investments are made at irregular intervals (e.g. SIPs).",
    "AUM (Assets Under Management)": "Total market value of all assets managed by a mutual fund scheme.",
    "Expense Ratio": "Annual fee charged by the fund as a percentage of AUM.",
    "Exit Load": "A fee charged for withdrawing money before a certain period.",
    "Lock-in Period": "Duration during which you cannot withdraw your investment (e.g., 3 years for ELSS).",
    "Regular SIP": "Fixed amount invested at fixed intervals.",
    "Top-Up SIP / Step-Up SIP": "SIP amount increases automatically over time.",
    "Flexible SIP": "You can change the SIP amount based on cash flow.",
    "Perpetual SIP": "No end date unless canceled manually.",
    "Trigger SIP": "Automatically starts or stops based on market conditions or NAV.",
    "Frequency": "Interval of investment (e.g., monthly, quarterly).",
    "Tenure": "Total duration for which SIP is to be made.",
    "Goal-Based SIP": "SIPs designed for specific goals (education, retirement, etc.).",
    "STP (Systematic Transfer Plan)": "Transfers money between schemes at regular intervals.",
    "SWP (Systematic Withdrawal Plan)": "Withdraws money from mutual funds at regular intervals.",
    "ELSS (Equity-Linked Saving Scheme)": "Tax-saving mutual fund under Section 80C.",
    "Capital Gains": "Profits made from selling mutual fund units.",
    "LTCG (Long-Term Capital Gains)": "Gains on equity funds held for over 1 year, taxed above ₹1 lakh/year.",
    "STCG (Short-Term Capital Gains)": "Gains on equity funds held for under 1 year, taxed at 15%.",
    "Account Number": "Unique number assigned to your bank account.",
    "IFSC Code": "Code used to identify bank branches for NEFT/RTGS/IMPS transactions.",
    "MICR Code": "Magnetic code on cheques for faster processing.",
    "Branch": "Physical location of a bank.",
    "Balance": "The current amount of money in an account.",
    "Savings Account": "For saving money; earns interest.",
    "Current Account": "Meant for frequent transactions; no interest.",
    "Fixed Deposit (FD)": "Lump sum deposited for a fixed time at higher interest.",
    "Recurring Deposit (RD)": "Monthly deposits with fixed maturity and interest.",
    "NRI Account (NRE/NRO)": "For Indians living abroad to manage funds in India.",
    "NEFT": "Nationwide transfer, settles in batches.",
    "RTGS": "Real-time transfer for large amounts (₹2L+).",
    "IMPS": "24x7 real-time small fund transfer.",
    "UPI": "Unified Payments Interface, instant mobile payments.",
    "Cheque": "Written order directing bank to pay money.",
    "Demand Draft (DD)": "Prepaid payment instrument issued by banks.",
    "Debit Card": "Directly linked to your account; money debited instantly.",
    "Credit Card": "Borrowed money; repaid later with interest if overdue.",
    "CVV": "3-digit code on back of cards for authentication.",
    "Net Banking": "Online interface to manage bank account.",
    "Mobile Banking": "Banking services through smartphone apps.",
    "OTP": "One-Time Password for authenticating transactions.",
    "Loan": "Borrowed money repayable with interest.",
    "EMI (Equated Monthly Installment)": "Fixed monthly payment towards a loan.",
    "Interest Rate": "Percentage charged on borrowed amount.",
    "Collateral": "Asset pledged against a loan.",
    "Credit Score": "A number that represents your creditworthiness.",
    "Overdraft": "Allows you to withdraw more than your account balance.",
    "Statement": "A summary of transactions in an account.",
    "Minimum Balance": "The least balance required to avoid penalties.",
    "Penalty Charges": "Fees levied for violating banking terms (e.g. minimum balance).",
    "Service Charge": "Charges for banking services.",
    "KYC (Know Your Customer)": "A process for verifying the identity and address of customers to prevent fraud, money laundering, and terrorist financing.",
    "PAN (Permanent Account Number)": "Used for tax reporting and large transactions.",
    "Aadhaar": "Biometric ID used for linking bank accounts in India.",
    "CIF Number": "Unique number that represents a customer’s profile across accounts.",
    "PIN": "Personal Identification Number for ATMs/cards.",
    "Phishing": "Fraudulent attempt to get sensitive information.",
    "Two-Factor Authentication": "Uses two levels of security (e.g., password + OTP).",
    "SSL Encryption": "Encrypts data during online banking sessions.",
    "Customer Due Diligence (CDD)": "The standard process of identifying and verifying a customer's identity, assessing risk, and monitoring transactions.",
    "Enhanced Due Diligence (EDD)": "Additional checks performed on high-risk customers, such as PEPs, including verifying source of funds and continuous monitoring.",
    "Simplified Due Diligence (SDD)": "A relaxed KYC process for low-risk customers or transactions, requiring fewer identity checks.",
    "Politically Exposed Person (PEP)": "Individuals with prominent public functions (e.g., politicians, military officials) requiring higher scrutiny due to corruption risk.",
    "Beneficial Owner": "The individual who ultimately owns or controls an account or transaction, even if not the account holder.",
    "KYC Documents": "Official documents used for identity and address verification, like Aadhaar, PAN, passport, utility bills, etc.",
    "e-KYC (Electronic KYC)": "A digital method of completing KYC using Aadhaar or video authentication to verify identity online.",
    "Periodic KYC Update / Re-KYC": "The mandatory periodic review and updating of customer details to stay compliant with KYC norms.",
    "KYC Norms/Guidelines": "Regulations issued by authorities like the RBI that banks must follow for proper KYC implementation.",
    "Risk-Based KYC": "Adjusting the level of due diligence based on the customer's risk profile (low, medium, or high risk).",
    "KYC Registry (CKYCR)": "A centralized database (e.g., Central KYC Registry in India) that stores and allows access to customer KYC records across financial institutions.",
    "Principal Amount": "The original sum of money borrowed from the lender, on which interest is calculated.",
    "Reducing Balance Method": "Interest is calculated on the outstanding principal after each EMI payment, resulting in lower interest over time.",
    "Flat Interest Rate": "Interest is calculated on the full principal amount for the entire loan tenure, regardless of payments already made.",
    "Loan Tenure": "The total time period over which the loan is to be repaid through EMIs, typically measured in months or years.",
    "Amortization Schedule": "A detailed table showing each EMI’s breakdown into interest and principal components over the loan tenure.",
    "Prepayment": "The option for the borrower to pay off part (or all) of the loan before the tenure ends, possibly incurring a penalty or saving on interest.",
    "Foreclosure": "The complete repayment of the loan amount before the end of the loan term, closing the loan account.",
    "EMI Bounce": "A situation where the borrower's EMI payment fails (e.g., due to insufficient balance), usually incurring a penalty.",
    "NACH Mandate": "National Automated Clearing House authorization allowing automatic EMI deductions from the borrower’s bank account.",
    "EMI in Arrears": "The EMI is paid after the completion of the month for which it is due (common in personal and home loans).",
    "EMI in Advance": "The first EMI is paid at the time of disbursement, and the rest are paid monthly (common in car loans).",
    "Floating Interest Rate": "An interest rate that varies based on changes in benchmark rates, affecting EMI amounts over time.",
    "Fixed Interest Rate": "An interest rate that remains constant throughout the loan tenure, keeping EMI amounts unchanged.",
    "EMI Calculator": "A digital tool used to calculate EMI amounts based on loan amount, interest rate, and tenure.",
    "PAN Card": "The physical document issued by the government containing the PAN, name, photo, date of birth, and signature of the individual or entity.",
    "Form 49A": "The application form used by Indian citizens to apply for a new PAN card.",
    "Form 49AA": "The application form used by foreign nationals/entities to apply for a PAN card in India.",
    "Mandatory PAN Usage in Banking": "PAN is required for transactions above prescribed limits (e.g., cash deposits/withdrawals above ₹50,000, opening accounts, high-value investments).",
    "PAN-Aadhaar Linking": "Mandatory linking of PAN with Aadhaar to validate and continue using the PAN for financial and banking activities.",
    "PAN Validation": "The process banks follow to verify the authenticity of a customer's PAN with the Income Tax Department.",
    "PAN for Minor": "PAN can be issued in the name of a minor; the parent/guardian’s PAN may also be required for account operations.",
    "PAN for Non-Individual Entities": "Companies, firms, trusts, and other legal entities must have a PAN for opening bank accounts and tax-related compliance.",
    "PAN Exemptions": "Certain small-value banking transactions (like small deposit accounts under PMJDY) may be exempted from mandatory PAN requirement.",
    "PAN Quoting for TDS": "PAN must be quoted for any TDS (Tax Deducted at Source) transactions; otherwise, higher TDS rates may apply.",
    "PAN in KYC": "PAN is a mandatory document for KYC in banks to verify customer identity and track financial behavior.",
    "PAN and Form 60": "If a person doesn’t have a PAN, they must submit Form 60 when making high-value transactions (like fixed deposits, buying property, etc.).",
    "PAN Status Tracking": "Customers can track the status of their PAN application or changes via NSDL or UTIITSL portals.",
    "Duplicate PAN Card": "A reissued PAN card when the original is lost, damaged, or incorrect details need correction.",
    "Bank Locker / Safe Deposit Locker": "A secured storage facility provided by a bank for customers to store valuables like jewelry, documents, or other important items.",
    "Locker Agreement": "A legal contract between the bank and the customer outlining the terms and conditions of using the locker facility.",
    "Locker Rent": "The annual or periodic fee charged by the bank to the customer for using the locker, depending on its size and branch location.",
    "Nomination Facility": "A facility allowing the locker holder to nominate a person who can access the locker contents in case of the holder’s death.",
    "Locker Key": "A physical key given to the customer to operate the locker; most lockers require dual control (bank and customer keys).",
    "Joint Locker": "A locker operated by more than one person (joint holders), where access rules depend on the operational mandate (e.g., either or survivor).",
    "Custodian Key": "A master key held by the bank which is required, along with the customer’s key, to open the locker (dual key system).",
    "Safe Custody": "A separate service from lockers where customers can deposit valuable items/documents for safekeeping by the bank without renting a locker.",
    "Locker Access Register": "A record maintained by the bank noting the date and time of each access to the locker by the customer or nominee.",
    "Surrender of Locker": "The process where the customer voluntarily closes the locker facility and returns the key; the bank refunds the deposit (if applicable).",
    "Locker Breaking": "If a customer fails to pay rent or is untraceable for a long time, the bank may break open the locker after due process and notice.",
    "Security Deposit / FDR (Fixed Deposit Receipt)": "Some banks require customers to keep a fixed deposit as collateral for locker rent or future dues.",
    "Liability of Bank": "As per RBI guidelines, banks have limited liability for locker contents unless loss/damage occurs due to negligence or fraud on the bank’s part.",
    "RBI Locker Guidelines (2021)": "Regulations issued by the Reserve Bank of India to improve transparency, safety, and grievance redressal in locker operations.",
    "Indemnity Bond": "A legal document that may be required from a nominee or legal heir before handing over locker contents in the absence of a clear nominee.",
    "Credit Score": "A number representing your creditworthiness.",
    "Credit Report": "A detailed history of your credit activity and accounts.",
    "Debit Card": "A card that deducts money directly from your bank account.",
    "Credit Card": "A card that lets you borrow money up to a certain limit.",
    "Loan": "Money borrowed that must be paid back with interest.",
    "Mortgage": "A loan specifically for buying property.",
    "Overdraft": "Spending more than you have in your bank account, creating a negative balance.",
    "APR (Annual Percentage Rate)": "The yearly interest rate on loans or credit cards.",
    "Stock": "Ownership in a company.",
    "Bond": "A loan to a company or government that pays you interest over time.",
    "Dividend": "A portion of a company’s profits paid to shareholders.",
    "Portfolio": "A collection of investments (stocks, bonds, etc.).",
    "Mutual Fund": "A pool of money from many investors used to buy a diversified portfolio.",
    "ETF (Exchange-Traded Fund)": "Similar to a mutual fund but traded like a stock.",
    "Capital Gain": "Profit from selling an investment at a higher price than you bought it.",
    "Risk Tolerance": "Your ability and willingness to handle investment losses.",
    "Bull Market": "A market condition where prices are rising.",
    "Bear Market": "A market condition where prices are falling.",
    "Taxable Income": "The portion of your income that is subject to taxes.",
    "Tax Deduction": "An expense that reduces your taxable income.",
    "Tax Credit": "A direct reduction of your tax bill.",
    "Income Tax": "Tax paid on earnings from work or investments.",
    "Capital Gains Tax": "Tax on profits from selling investments.",
    "Pension": "A retirement plan that provides a fixed payment.",
    "401(k)/Public Provident Fund (PPF)": "Retirement savings plans (US/India example).",
    "IRA (Individual Retirement Account)": "A US-based retirement savings account.",
    "Premium": "The cost you pay for insurance coverage.",
    "Deductible": "The amount you pay before insurance covers the rest.",
    "Coverage": "The extent of protection provided by an insurance policy.",
    "Life Insurance": "Pays money to beneficiaries when the insured person dies.",
    "Health Insurance": "Covers medical expenses.",
    "Revenue": "The total income a business earns.",
    "Profit": "Revenue minus expenses.",
    "Loss": "When expenses are more than revenue.",
    "Cash Flow": "The money coming in and going out of a business.",
    "Balance Sheet": "A financial statement showing assets, liabilities, and net worth.",
    "Income Statement": "A report showing profit or loss over time.",
    "GDP (Gross Domestic Product)": "The total value of goods and services produced in a country.",
    "Recession": "A period of economic decline.",
    "Diversification": "Spreading investments to reduce risk.",
    "Annuity": "A fixed sum of money paid to someone each year, often for retirement.",
    "Yield": "The earnings from an investment, usually shown as a percentage.",
    "Equity": "Ownership interest in an asset or company (e.g., stock or home equity).",
    "Liquidity": "How quickly an asset can be converted into cash.",
    "Roth IRA": "A retirement account where withdrawals are tax-free.",
    "Traditional IRA": "A retirement account with tax-deductible contributions but taxed withdrawals.",
    "Hedge": "A strategy to reduce investment risk.",
    "Speculation": "High-risk investment aiming for high returns.",
    "Real Estate Investment Trust (REIT)": "A company that owns or finances income-producing real estate.",
    "Derivatives": "Financial contracts whose value depends on an underlying asset.",
    "IPO (Initial Public Offering)": "When a company first sells shares to the public.",
    "Market Capitalization": "Total value of a company’s shares (stock price × shares outstanding).",
    "Blue Chip Stock": "A well-established, financially sound company.",
    "Penny Stock": "Low-priced, high-risk stocks of small companies.",
    "Index": "A group of stocks used to represent the performance of the market (e.g., Nifty 50, S&P 500).",
    "Volume": "The number of shares traded during a time period.",
    "Volatility": "How much and how quickly an investment’s price changes.",
    "Bid Price": "The price a buyer is willing to pay for a stock.",
    "Ask Price": "The price a seller wants for a stock.",
    "Market Order": "An order to buy/sell immediately at the current market price.",
    "Accounts Payable": "Money a company owes to suppliers.",
    "Accounts Receivable": "Money customers owe to a company.",
    "Depreciation": "The reduction in value of an asset over time.",
    "Amortization": "Gradual repayment of a loan or spreading cost of an intangible asset.",
    "Accrual": "Recording income/expenses when they occur, not when cash changes hands.",
    "Gross Income": "Total income before deductions or taxes.",
    "Operating Income": "Profit from business operations (revenue - operating expenses).",
    "EBITDA": "Earnings before interest, taxes, depreciation, and amortization.",
    "Break-even Point": "When income equals expenses (no profit or loss).",
    "Return on Investment (ROI)": "Profit from an investment expressed as a percentage.",
    "GST (Goods and Services Tax)": "A value-added tax in India on goods/services.",
    "Excise Tax": "A tax on specific goods like alcohol or fuel.",
    "Withholding Tax": "A portion of income withheld for taxes before payment.",
    "Form 16": "A certificate issued by employers in India for TDS (tax deducted at source).",
    "Subsidy": "Financial assistance from the government to reduce the cost of goods/services.",
    "Tax Bracket": "The income range taxed at a specific rate.",
    "Audit": "An official examination of financial records.",
    "PAN (Permanent Account Number)": "A unique tax ID issued in India.",
    "Filing Status": "Category used to determine your tax rates (e.g., single, married).",
    "Income Tax Return (ITR)": "A form to report income and taxes to the government.",
    "Emergency Fund": "Savings for unexpected expenses (like job loss, medical bills).",
    "Financial Literacy": "Understanding how money works and how to manage it.",
    "Impulse Buying": "Buying something without planning or need.",
    "Frugality": "Being careful with money; avoiding unnecessary expenses.",
    "Opportunity Cost": "The loss of potential gain from choosing one option over another.",
    "Pay Yourself First": "Saving a portion of income before spending on anything else.",
    "Lifestyle Inflation": "Spending more as you earn more.",
    "Zero-Based Budget": "A budgeting method where every dollar is assigned a purpose.",
    "Financial Freedom": "Having enough savings/investments to live without needing to work.",
    "Debt Snowball Method": "Paying off smallest debts first to gain momentum.",
    "Accrued Interest": "Interest that has been earned but not yet paid or received.",
    "Adjustable-Rate Mortgage (ARM)": "A mortgage with interest rates that can change over time.",
    "Annual Percentage Rate (APR)": "The total yearly cost of a loan, including interest and fees.",
    "Annuity": "A financial product that pays out a fixed stream of payments, often for retirees.",
    "Appreciation": "An increase in the value of an asset over time.",
    "Asset Class": "A group of investments with similar characteristics, like stocks, bonds, or real estate.",
    "Automatic Transfer": "A scheduled movement of money from one account to another.",
    "Back-End Load": "A fee charged when you sell a mutual fund.",
    "Balance Sheet": "A financial statement showing assets, liabilities, and net worth.",
    "Balloon Payment": "A large, final loan payment due at the end of a term.",
    "Bankruptcy": "A legal process for people or businesses unable to repay debts.",
    "Basis Point": "Equal to 0.01%; used to measure interest rate changes.",
    "Bearer Bond": "A bond not registered to a specific owner.",
    "Beneficiary": "A person who receives money from insurance or a will.",
    "Blue Chip Stock": "Stock from a well-established, financially sound company.",
    "Book Value": "The value of a company based on its financial statements.",
    "Bottom Line": "A company’s net income or profit.",
    "Break-Even Point": "When income equals expenses or investment equals return.",
    "Broker": "A person or firm that facilitates buying and selling of assets.",
    "Buy and Hold": "An investment strategy where assets are held long-term.",
    "Callable Bond": "A bond that can be redeemed by the issuer before maturity.",
    "Capital": "Wealth in the form of money or assets.",
    "Capital Expenditure": "Spending on physical assets like property or equipment.",
    "Capital Structure": "How a company finances operations (debt vs equity).",
    "Cash Flow": "The movement of money in and out of a business or individual account.",
    "Certified Financial Planner (CFP)": "A professional certified to offer financial advice.",
    "Claim Settlement Ratio": "Percentage of insurance claims an insurer pays out.",
    "Collateral": "An asset pledged against a loan.",
    "Commodities": "Basic goods like gold, oil, or wheat traded in markets.",
    "Consumer Price Index (CPI)": "Measures inflation by tracking consumer goods prices.",
    "Contingency Fund": "Money set aside for unexpected events.",
    "Corporate Bond": "A bond issued by a company to raise money.",
    "Cost of Living": "The amount of money needed to maintain a standard lifestyle.",
    "Credit Bureau": "Agencies that collect credit information to calculate credit scores.",
    "Credit Limit": "Maximum amount you can borrow on a credit card.",
    "Credit Utilization Ratio": "Percentage of your credit limit you're using.",
    "Custodian Bank": "A financial institution that holds securities for safekeeping.",
    "Day Trading": "Buying and selling stocks within the same day.",
    "Debt-to-Income Ratio (DTI)": "Compares monthly debt payments to gross income.",
    "Depreciation": "The decrease in value of an asset over time.",
    "Digital Wallet": "Electronic method of storing payment details (e.g., Google Pay).",
    "Direct Deposit": "Employer transfers salary directly into your bank account.",
    "Discount Rate": "The interest rate the central bank charges commercial banks.",
    "Dividend Yield": "Dividend per share divided by price per share.",
    "Dow Jones Industrial Average": "A stock market index of 30 large U.S. companies.",
    "Early Withdrawal Penalty": "Fee for withdrawing money from a retirement account early.",
    "Earnings Per Share (EPS)": "Company’s profit divided by outstanding shares.",
    "Economic Indicator": "Data used to assess the health of the economy.",
    "Escrow Account": "Temporary account where funds are held until a condition is met.",
    "Ex-Dividend Date": "The date after which a stock is bought without a dividend.",
    "Exchange Rate": "Value of one currency in relation to another.",
    "Expense Ratio": "Annual fee charged by mutual funds, expressed as a percentage.",
    "FICO Score": "A popular credit score model in the U.S.",
    "Financial Year": "A 12-month period used for accounting (April–March in India).",
    "Fixed Asset": "Long-term physical assets like buildings or land.",
    "Forex (Foreign Exchange)": "Global market for trading currencies.",
    "Futures Contract": "An agreement to buy/sell an asset at a future date.",
    "GAAP (Generally Accepted Accounting Principles)": "Standard accounting rules.",
    "Grace Period": "Time during which no interest or penalty is charged.",
    "Gross Income": "Total income before taxes and deductions.",
    "Growth Stock": "A stock expected to grow faster than the market.",
    "Guarantor": "A person who agrees to repay a loan if the borrower can’t.",
    "Holding Period": "Time you own an investment before selling.",
    "Idle Money": "Cash that is not earning any return.",
    "Index Fund": "A fund that tracks a stock market index.",
    "Inflation Index Bond": "Bond adjusted for inflation.",
    "Installment": "A fixed payment made periodically to repay a loan.",
    "Interest Coverage Ratio": "Measures a firm’s ability to pay interest.",
    "Internal Rate of Return (IRR)": "Discount rate that makes net present value zero.",
    "Insolvency": "Inability to pay debts when due.",
    "Inventory": "Goods a company holds for sale.",
    "Joint Account": "A bank account owned by two or more people.",
    "Leasing": "Renting an asset for use without ownership.",
    "Letter of Credit": "A guarantee from a bank for payments in trade.",
    "Liquidity Ratio": "Measures ability to meet short-term obligations.",
    "Loan-to-Value Ratio (LTV)": "Loan amount divided by appraised asset value.",
    "Lock-in Period": "Time before which investments cannot be withdrawn.",
    "Market Capitalization": "Total market value of a company’s shares.",
    "Money Market": "Short-term debt trading market.",
    "Monopoly": "Market with a single seller",
    "Mortgage": "A loan secured by real estate.",
    "NAV (Net Asset Value)": "Price of one unit of a mutual fund.",
    "Negative Balance": "When expenses exceed account balance.",
    "Nominal Interest Rate": "The interest rate before inflation adjustment.",
    "Non-Performing Asset (NPA)": "A loan where repayment is overdue.",
    "Options Contract": "Right (not obligation) to buy or sell an asset later.",
    "Over-the-Counter (OTC)": "Trading outside formal exchanges.",
    "Par Value": "The face value of a bond or stock.",
    "Pension Fund": "A fund set aside to pay retiree benefits.",
    "Portfolio Rebalancing": "Adjusting asset allocation to maintain goals.",
    "Pre-Tax Income": "Income before taxes are deducted.",
    "Principal": "The original amount of money borrowed or invested.",
    "Quick Ratio": "Measures ability to pay liabilities with liquid assets.",
    "Redemption": "Selling or repaying an investment.",
    "Return on Equity (ROE)": "Profitability relative to shareholders’ equity.",
    "Reverse Mortgage": "A loan for seniors against home equity, paid later.",
    "Secured Loan": "A loan backed by collateral.",
    "Systematic Risk": "Risk affecting the entire market.",
    "Yield": "Earnings from an investment over time, typically expressed as a percentage."

};
const example1 = {
    "Asset": "A house that grows in value each year, A bond or stock that brings good cheer, These are assets, strong and true, They work for you in all you do.",
    "Liability": "A loan you owe, a bill unpaid, A burden that makes you feel afraid, Liabilities hold you down with weight, They shape your financial fate.",
    "Net Worth": "Assets shine and debts subtract, Net worth shows the final fact, What you own minus what you owe, Is the true wealth status you show.",
    "Income": "Salary, rent, or dividends too, Income is money that flows to you, The stream that feeds your daily bread, And fills the path that lies ahead.",
    "Expense": "Bills and rent, food on the plate, Every rupee you circulate, Expenses flow from pocket to air, Leaving your wallet a little bare.",
    "Budget": "A roadmap for your cash to steer, With every goal set sharp and clear, A budget helps you plan each cent, So you know just where it went.",
    "Savings": "A coin today, a treasure tomorrow, Savings ease your future sorrow, Stored in banks or tucked away, They shine on a rainy day.",
    "Interest": "A fee you earn or a price you pay, Interest works both night and day, It grows your funds or adds to debt, Depending on how the deal is set.",
    "Compound Interest": "Interest on interest, year by year, A magic trick that makes gains clear, It grows like trees from tiny seeds, Fulfilling dreams and future needs.",
    "Inflation": "Prices rise, your rupees shrink, Inflation changes how we think, A loaf today may double in rate, If time and costs do not abate.",
    "SIP": "Bit by bit, you plant a seed, An SIP meets every need, Month by month, your wealth will grow, With market tides that ebb and flow.",
    "NAV": "The NAV tells the value true, Of one fund unit, fresh and new, It shifts each day as markets sway, Revealing what your funds will pay.",
    "Units": "Each unit is a piece you own, Of mutual funds where wealth is grown, The more you buy, the more your share, In market moves that rise and flare.",
    "Mutual Fund": "Many stocks, yet just one buy, A mutual fund lets risks run dry, Managed by pros who scan the charts, It balances gains from various parts.",
    "AMC": "An AMC guards your fund with care, It chooses stocks with thought and flair, It runs the schemes, tracks every trend, To bring returns that upward bend.",
    "Fund Manager": "The fund’s captain, sharp and wise, With eyes on markets, lows, and highs, The fund manager picks each share, With strategy, caution, and utmost care.",
    "Scheme": "A scheme's a plan your fund may take, Each with a goal and risk it’ll stake, Growth or income, short or long, It sings a different money song.",
    "ROI": "ROI tells you loud and clear, Was the gain worth what you put here? A simple way to judge the ride, Of money placed and profit’s tide.",
    "CAGR": "CAGR speaks in quiet grace, Of how investments win the race, Year by year, it tracks the climb, And smooths the bumps across the time.",
    "XIRR": "When cash flows shift and dates aren't neat, XIRR keeps returns complete, It tells the rate through chaos and strife, Of every inflow in your financial life.",
    "AUM": "All the wealth a fund does hold, From timid youth to investors bold, AUM shows the trust amassed, In schemes both steady, slow, or fast.",
    "Expense Ratio": "A silent bite from gains you earn, Expense ratio’s what they take in turn, For managing funds and keeping pace, It’s the cost you pay for market race.",
    "Exit Load": "If you sell your fund too soon, Exit load will play its tune, A little fee for leaving fast, So stay a while, let profits last.",
    "Lock-in Period": "Money parked but not yet free, A lock-in holds it like a key, Three years or five, it must reside, Till time unlocks and gates are wide.",
    "Regular SIP": "Month by month, like steady rain, A regular SIP eases the strain, It builds a habit, sure and slow, And helps your wealth begin to grow.",
    "Top-Up SIP": "Start small, then grow your stake, With Top-Up SIP, that’s the take, As income grows, so can your pay, To build more wealth, the wiser way.",
    "Flexible SIP": "Skip a month or change the sum, Flexible SIPs are never glum, Life's surprises, they allow, Adjust your plan to suit the now.",
    "Perpetual SIP": "No end date in the chosen span, A SIP that flows as long as it can, Perpetual plans just carry on, Till you stop or wealth is gone.",
    "Trigger SIP": "A market move, a price that dips, Can trigger your SIP in quick flips, It buys when low or signals flash, To enter smart with lesser cash.",
    "Frequency": "Daily, weekly, monthly ways, Frequency shapes how your SIP plays, Choose the pace that suits you well, It’s how your investment will swell.",
    "Tenure": "The longer you stay, the better the yield, With compound gains your shield and field, Tenure speaks of time and grace, To let your money find its place.",
    "Goal-Based SIP": "Set your goal and match the rate, Let your SIP decide the fate, With purpose clear and discipline tight, Your dreams take form in money’s light.",
    "STP (Systematic Transfer Plan)": "From one fund to another you glide, Reducing risk with every stride, It’s balance, timing, thoughtful art, STP plays a patient part.",
    "SWP (Systematic Withdrawal Plan)": "It withdraws slow, not all at once, While your capital grows, not just pounce, For steady cash and peace of mind, SWP is well-designed.",
    "ELSS (Equity Linked Savings Scheme)": "A mutual fund with a saving twist, With Section 80C on its list, High returns, yet risks may sway, ELSS makes taxes pay.",
    "Capital Gains": "Buy it low and sell it high, Watch your money multiply, Gains are sweet, but taxes wait, Plan ahead to navigate.",
    "LTCG (Long-Term Capital Gains)": "Stocks and funds that age with grace, Bring rewards at slower pace, LTCG says long-term wins, In wealth creation’s wiser spins.",
    "STCG (Short-Term Capital Gains)": "In under a year if profits show, Short-term gains are taxed, you know, So weigh the time and what you earn, For every gain takes its turn.",
    "Account Number": "Like a name for your cash’s door, It guards your balance, spends, and more, Unique to you, a vital thread, Where money rests and dreams are fed.",
    "IFSC Code": "Eleven characters, smart and tight, It guides your money day or night, Without this code, funds may not land, So keep it close, like money’s hand.",
    "MICR Code": "A unique number for your branch, To help your cheques securely launch, It speeds up banking — less delay, And clears your payments the swiftest way.",
    "Branch": "Though apps have come to take the lead, The branch still serves your rarest need, A place of people, papers, plan, Where finance meets the helping hand.",
    "Balance": "It tells your worth at any hour, The base from which you rise or cower, So track it close, and treat it right, Your balance shines in finance light.",
    "Savings Account": "Safe and simple, easy to reach, A first step in the finance beach, Withdraw, deposit, pay with ease, Savings accounts are meant to please.",
    "Current Account": "High transactions, frequent flow, No limits where your dealings go, A business tool that’s sharp and bright, To keep your trade both swift and right.",
    "Fixed Deposit": "With higher rates than savings hold, Your money rests in interest’s fold, Though early breaks may cost you fine, It’s still a safe and strong design.",
    "Recurring Deposit": "Monthly sums, a fixed affair, With time and interest playing fair, It teaches habits, saves with grace, To reach your goal at your own pace.",
    "NRI Account": "NRE or NRO, choose your way, To manage rupees every day, An NRI’s banking, custom made, With global reach and Indian shade.",
    "NEFT (National Electronic Funds Transfer)": "For payments, bills, or family send, NEFT is your trusted friend, It takes its time, but not too slow, And always helps your money flow.",
    "RTGS (Real-Time Gross Settlement)": "No batching here, just single fire, For urgent moves that banks require, Minimum limits, maximum trust, RTGS is safe and just.",
    "IMPS (Immediate Payment Service)": "No time slots, no waiting game, Send with mobile, name, or name, When time is short and speed is key, IMPS moves instantly.",
    "UPI (Unified Payments Interface)": "Real-time cash with zero fee, UPI sets your payments free, India’s pride, a tech delight, With UPI, you pay it right.",
    "Cheque": "Old but gold, still trusted much, For formal deals, a classic touch, Crossed or bearer, issued slow, But solid where big payments go.",
    "Demand Draft": "The bank itself will guarantee, That funds are paid securely, No bounce, no bluff — it clears with pride, A secure path for money’s ride.",
    "Debit Card": "Linked to account, it pays with ease, For groceries, clothes, and travel fees, No borrowing, just what you’ve got, A handy tool in every spot.",
    "Credit Card": "Rewards and points and cashback too, But pay on time, or fees pursue, A useful friend if you stay wise, Or traps you in debt’s dark disguise.",
    "CVV (Card Verification Value)": "Each transaction needs this shield, A silent lock your card must wield, So never share, and keep it clear, Your CVV defends what's dear.",
    "Net Banking": "With password strong and smart two-step, You guard your funds from digital theft, From home or far, you’re never stuck, Net banking keeps you in control and luck.",
    "Mobile Banking": "From alerts to scans to balance check, Your mobile app keeps things in check, Fast and sleek, so smooth to steer, Banking now is always near.",
    "OTP (One-Time Password)": "It comes and goes within a minute, But while it lasts, your safety’s in it, So never share this short-lived key, Your OTP is privacy’s plea.",
    "Loan": "But loans must end where they began, With payments made as per the plan, With care and time, repay your share, And build your credit with repair.",
    "EMI": "For homes or cars or student dues, EMIs help your goals come true, Just don’t delay or miss your date, Or penalties may escalate.",
    "Interest Rate": "Fixed or floating, high or low, It shapes the way your money’ll grow, Understand it well and clear, For it can cost or bring you cheer.",
    "Collateral": "A home, a bond, or car you keep, If risk is deep, the cost runs steep, So pledge with care, know what’s at stake, Or you may lose more than you make.",
    "Credit Score": "Pay on time, don’t borrow wild, Your credit score stays calm and mild, Above 750, you’re doing fine, A golden gate to rates benign.",
    "Overdraft": "Used with care, it saves the day, But reckless use may make you pay, A buffer zone when times get tight, Overdraft helps your balance fight.",
    "Statement": "Credits, debits, charges too, It shows you what your money knew, A vital scroll to check and guard, Your statement keeps your records starred.",
    "Minimum Balance": "So keep a buffer, know your rule, Or banks will treat you like a fool, A simple step to save some fees, Let balance rest with banking ease.",
    "Penalty Charges": "Stay alert and plan your moves, Avoid the charges no one loves, For every misstep has a cost, And careless funds can soon be lost.",
    "Service Charge": "Though small at first, they can grow bold, If not reviewed or clearly told, So read your terms and understand, Where service charges softly land.",
    "KYC": "Your name, your face, your ID proof, They check it all beneath one roof, A safety step that you must clear, Before your bank account is near.",
    "PAN": "From income proof to high spends made, PAN tracks the paths your payments laid, Without this card, you might get stuck, For PAN is law, not random luck.",
    "Aadhaar": "For subsidies, for KYC, Aadhaar helps you easily, Link it well and guard it tight, It holds your data, day and night.",
    "CIF Number": "From contact info to your plan, The CIF shows all that you began, Banks use this file to understand, The customer in their command.",
    "PIN": "Never share and never write, Keep it secret, keep it tight, It’s your key, your silent sword, Protects your funds without a word.",
    "Phishing": "Beware the site that looks too neat, And never type where frauds might meet, Phishing hides in friendly dress, But leaves behind a banking mess.",
    "Two-Factor Authentication": "It may be face, a code, or mail, But two steps make the hackers fail, So never skip this safety key, It guards your account easily.",
    "SSL Encryption": "Without it, data’s plain to see, With SSL, it’s mystery, Encrypted paths keep safe your wealth, Protects your privacy and health.",
    "Customer Due Diligence": "Checks on who you really are, To keep the system safe by far, Preventing fraud, money’s misuse, This diligence is a strong noose.",
    "Enhanced Due Diligence": "For clients flagged or deals unclear, More scrutiny comes near, To curb the risks and fight the crime, This step is done each time.",
    "Simplified Due Diligence": "For safe clients and low-risk flow, Simplified checks quickly go, To ease the load and speed the pace, Without too deep a chase.",
    "Politically Exposed Person": "Such people need extra care, To stop corruption’s snare, Their dealings watched with keenest eye, To keep the system clean and high.",
    "Beneficial Owner": "Who really owns beyond the sheet? The one who earns the profit sweet, Hidden behind legal screens, The beneficial owner gleans.",
    "KYC Documents": "Drivers license or utility bill, Proof of address and ID still, Collecting these with care and grace, Ensures your profile finds its place.",
    "e-KYC": "Faster, easier, paper-free, Using tech for identity, With OTPs and biometric scans, You prove your self in quicker plans.",
    "Periodic KYC Update": "Old data fades or falls behind, So banks request you to remind, Update your info once a while, To keep your records in a file.",
    "KYC Norms": "Set by regulators with a plan, To guard the banking system’s span, Following rules both strict and fair, Protecting customers with care.",
    "Risk-Based KYC": "Based on risk, checks vary wide, From simple to strict inside, Tailored screening fits the need, To help the bank and client proceed.",
    "KYC Registry": "A database where info stays, To share between banks in ways, So opening accounts is fast, And fraud detection’s built to last.",
    "Principal Amount": "It’s what you borrowed at the start, Before the interest takes its part, Pay this down to cut your dues, And save on money you must lose.",
    "Reducing Balance Method": "As each EMI chips away, Interest drops day by day, Your dues shrink and so do costs, Saving money at all costs.",
    "Flat Interest Rate": "Though simple, it may cost more, Since interest’s on the full core, Regardless of the shrinking loan, You pay more than you’ve been shown.",
    "Loan Tenure": "Choose it wisely, short or long, It affects how debts prolong, Longer means smaller pay each day, But total interest may outweigh.",
    "Amortization Schedule": "With every payment that you make, The schedule shows the balance break, Principal and interest split, Helping you to stay well lit.",
    "Prepayment": "Pay early to lessen cost, And stop the interest line at most, Free yourself from debt’s tight hold, Prepayment makes your story told.",
    "Foreclosure": "One final pay and debts are gone, No more EMIs to lean upon, Though some fees may apply ahead, Foreclosure frees your future tread.",
    "EMI Bounce": "Miss your date and troubles start, Bounce fees come and hurt your heart, Credit score takes a quick hit, So timely pay to stay legit.",
    "NACH Mandate": "Automated debit for your ease, No worries, no manual fees, Your EMIs leave on their own, So loans repay without a groan.",
    "EMI in Arrears": "You pay after the month has passed; EMI in arrears comes at the end, like rent you pay, not money you lend.",
  "EMI in Advance": "Pay before the month begins and cut down on the interest spins; EMI in advance saves time and trims a bit off repayment climb.",
  "Floating Interest Rate": "It rides the tide and shifts with time, this rate may rise or sometimes climb; it moves with market’s daily beat, so savings come when rates retreat.",
  "Fixed Interest Rate": "Unchanging as the silent moon, this rate won’t shift or alter soon; what you sign is what you get, no hidden swings, no payment threat.",
  "EMI Calculator": "A digital guide, both smart and quick, it helps you plan, just take your pick; input rate, amount, and time, it shows the EMI in perfect rhyme.",
  "PAN Card": "Your ID for the finance track with ten bold digits, alphanumeric stack; it links you to your tax and spend, and helps your filings start and end.",
  "Form 49A": "An Indian soul with tax in sight fills 49A to get things right; this form is key for PAN request to keep your finances at their best.",
  "Form 49AA": "For foreigners who deal or stay, Form 49AA clears the way; to get a PAN and pay with pride, and let their tax be bona fide.",
  "Mandatory PAN Usage in Banking": "For large deposits, mutual funds or trading shares and savings runs, PAN is now a must-have key to prove your name financially.",
  "PAN-Aadhaar Linking": "Two IDs strong must now unite to make your records firm and right; link PAN to Aadhaar, don’t delay or your PAN may lose its way.",
  "PAN Validation": "To check if PAN is real or fake, there’s a tool the portals make; type the code and see the match and verify if fraud may hatch.",
  "PAN for Minor": "A minor too can get their card for future steps or banking guard; with guardian's help and docs in hand, the minor PAN is in demand.",
  "PAN for Non-Individual Entities": "Companies, trusts, and firms that trade need PAN cards too, their dues to aid; not just people, but entities wide with legal names and tax applied.",
  "PAN Exemptions": "Some small folks or special cases are exempted from the PAN’s bases; when incomes fall below the line or rules decree they don’t combine.",
  "PAN Quoting for TDS": "When tax is cut at source with care, your PAN is needed everywhere; to link your income, track your dues, and claim your credits, no excuse.",
  "PAN in KYC": "Your PAN card joins your ID list; in KYC forms it can’t be missed; to prove your identity and tax, it’s crucial when the banker asks.",
  "PAN and Form 60": "If no PAN, there’s still a way; Form 60 helps you save the day; a declaration under law to state you lack PAN — nothing more.",
  "PAN Status Tracking": "After you apply and wait the queue, you can track what your PAN will do; online portals show the way to check if PAN has come your way.",
  "Duplicate PAN Card": "If your card is lost or torn, apply again without much scorn; duplicate PAN can be made to keep your finances well displayed.",
  "Bank Locker": "A safe within the bank’s strong wall to keep your jewels and papers all; locked and guarded, only you can access what is stored true.",
  "Locker Agreement": "To rent a locker, you must sign an agreement that sets the line of rules, rights, and duties clear to keep your belongings safe and near.",
  "Locker Rent": "For safety stored, you pay a fee; locker rent keeps theft from thee; usually yearly, sometimes more, it funds the bank’s secure door.",
  "Nomination Facility": "You name a person you trust and hold to claim your assets, your wealth, your gold; in case of absence, they take the claim, nomination keeps your wishes the same.",
  "Locker Key": "A tiny key that holds the power to open locks in safety’s bower; without it, access is denied, your secrets safe are well supplied.",
  "Joint Locker": "Two or more can share one space, a joint locker with a trusted base; both can access, both can store, together guarding treasure’s core.",
  "Custodian Key": "In banks where many hold the claim, the custodian key protects the same; only authorized hands can unlock the treasures held inside the stock.",
  "Safe Custody": "Keeping valuables in guarded trust, safe custody is a must; banks hold papers, bonds, and gold in safety’s vault, the story told.",
  "Locker Access Register": "Each time you open, close, or check, the access register keeps the trek; who entered when, and for what deed, this record tracks each access need.",
  "Surrender of Locker": "If you no longer need the space, you surrender locker’s place; return the key, clear your rent, and end the contract you had meant.",
  "Locker Breaking": "When keys are lost and access nil, the bank may break the locker still; in presence of you or law to open what you truly saw.",
  "Security Deposit": "To rent the locker, pay a fee; a deposit holds your safety key; it’s refundable when you leave, so banks have trust and you believe.",
  "Liability of Bank": "The bank’s duty to keep you safe, but also rules that set the chafe; they’re liable when they err or miss protecting clients’ wealth and bliss.",
  "RBI Locker Guidelines": "The RBI sets rules so clear for lockers safe, to calm your fear; regulating rent and access terms to keep your valuables from harms.",
  "Indemnity Bond": "An indemnity bond you sign with trust to promise safety, fair and just; if losses come or harm takes place, you’ll hold the bank in rightful grace.",
  "Credit Report": "Your financial story, laid bare and true, shows loans and cards and what you do; credit reports tell the bank’s mind if you’re trustworthy, or declined.",
  "Debit Card": "Plastic card linked to your cash; spend with swipe, your funds will dash; no credit given, just your own, pay instantly, funds are shown.",
  "Credit Card": "Plastic credit, borrowed pay; buy today, pay another day; with limits set and bills to clear, handle well, or debt may near.",
  "Mortgage": "A loan to buy your home or land with collateral close at hand; monthly EMIs pay the cost till ownership is fully crossed.",
  "APR (Annual Percentage Rate)": "The yearly cost of borrowed funds includes the fees and all the sums; APR shows what you really pay so loans and cards don’t hide away.",
  "Stock": "A tiny piece of company’s share, ownership proof if you dare; stocks can rise or fall with time, gains or losses in their rhyme."
};

const eg = {
    "Asset": "A car, a shop, a golden ring, Anything with wealth it’ll bring, An asset’s value tends to rise, Helping dreams materialize.",
    "Liability": "A debt that knocks on your door each day, From credit cards to EMIs you pay, Liabilities pull your balance sheet low, So manage them well, let savings grow.",
    "Net Worth": "Check the score of all you’ve made, From savings stacked to loans repaid, Your net worth climbs as debts decline, A measure of growth through money and time.",
    "Income": "Earnings each month that keep you afloat, A paycheck, a bonus, a freelance quote, The fuel for budgets, plans, and dreams, Income powers financial schemes.",
    "Expense": "From Netflix fees to cab you ride, Expenses hide on every side, Track them well, don’t let them sprawl, Control your outgo to stand tall.",
    "Budget": "Income in and spending out, A budget clears financial doubt, With discipline, it brings you peace, And helps your wealth and calm increase.",
    "Savings": "Save before you choose to spend, That’s the rule that pays in the end, Little by little, the sum will grow, And guard you when hard winds blow.",
    "Interest": "Earn it on savings, or pay it on loans, It’s the pulse in financial zones, A small percent, but strong and wise, Interest can swell or shrink your size.",
    "Compound Interest": "Reinvested wealth takes wings and flies, With compound power, your fortune lies, Start it early, let time befriend, And watch your savings greatly ascend.",
    "Inflation": "It eats the value in your pay, So invest smartly, don’t delay, Beat inflation with wiser tools, Not by stacking cash in pools.",
    "SIP": "A habit that builds with steady grace, Helping you in the money race, Low or high, you still invest, An SIP often proves the best.",
    "NAV": "It’s like a price tag on your share, In mutual funds placed here or there, Watch it rise or sometimes fall, NAV reflects the worth of all.",
    "Units": "A tiny slice of something grand, Units form your investment stand, Count them well, for they define, How much of profit will be thine.",
    "Mutual Fund": "Pooling money from the crowd, Mutual funds speak safe and loud, With diversification on their side, They take your savings for a ride.",
    "AMC": "A company with finance in its core, Managing wealth, opening doors, From SIPs to lumps it oversees, To help you grow your money trees.",
    "Fund Manager": "A thinker in the money game, Each move they make earns them fame, They steer the fund through storm and sun, Till profit and purpose are both won.",
    "Scheme": "Choose the scheme that suits your need, Some grow fast, while some take heed, It’s the wrapper round your fund so neat, That shapes your journey to complete.",
    "ROI": "A ratio that tells if it was wise, To chase that dream or compromise, High ROI brings happy cheer, It proves your cash was planted near.",
    "CAGR": "It shows how fast your value grew, Ignoring spikes that might confuse you, With CAGR’s help, you clearly see, The pace of growth, effectively.",
    "XIRR": "For SIPs or plans not uniform, XIRR becomes the measuring form, It paints the real returns you've gained, With all complexities explained.",
    "AUM": "The bigger it grows, the more it tells, How well the manager buys and sells, It's like the fund’s financial might, AUM reflects investor’s sight.",
    "Expense Ratio": "A lower ratio leaves more for you, A higher one may shrink your due, So scan it close, don’t overlook, It's written there in the fund's book.",
    "Exit Load": "It’s a charge for early leave, To help long-term plans achieve, So check the load before you sell, It’s in the fine print, clear as a bell.",
    "Lock-in Period": "No early exits, just sit tight, It teaches patience through the night, And once it's done, with time you win, With gains that grow from deep within.",
    "Regular SIP": "A fixed amount on a fixed day, It keeps impulsive spends at bay, No need to time the market's mood, Just stay the course—it does you good.",
    "Top-Up SIP": "An annual rise, pre-set, planned, More power in your savings hand, It fuels your future with a lift, A growing gift, a smarter shift.",
    "Flexible SIP": "No fixed chains to tie you tight, Change the rules, still grow it right, Adaptable, smart, and always fair, Your savings bend with gentle care.",
    "Perpetual SIP": "It never sleeps, it doesn’t rest, A saving stream at its best, Set it once, let it glide, And ride the market's turning tide.",
    "Trigger SIP": "Set the rule and let it run, When markets fall, the work is done, A disciplined, responsive style, Trigger SIP makes savings smile.",
    "Frequency": "More frequent buys may smooth the ride, Less may suit a cautious stride, But with the right rhythm in your plan, You’ll build your fortune hand in hand.",
    "Tenure": "The tenure marks the journey’s span, How long your savings’ race will run, A year, five, or even more, It helps your goals take shape and soar.",
    "Goal-Based SIP": "Not just for saving’s random sake, Goal-based SIPs are steps you take, For house, or car, or child's degree, Each rupee builds a future you see.",
    "STP (Systematic Transfer Plan)": "Shift your funds from debt to rise, With STP, be safe yet wise, A steady move, no rush or race, It finds the right time, the right place.",
    "SWP (Systematic Withdrawal Plan)": "You built your wealth through SIPs so neat, Now SWP brings monthly treat, A regular payout, smooth and sure, For post-retirement life secure.",
    "ELSS (Equity Linked Savings Scheme)": "Tax-saving meets equity’s flight, ELSS shines both bold and bright, With lock-in of just three years long, It helps your money grow strong.",
    "Capital Gains": "Sell a stock at higher rate, That’s capital gain — wealth at the gate, The difference’s taxed, it’s wise to know, How fast or slow your profits grow.",
    "LTCG (Long-Term Capital Gains)": "Hold for a year, maybe more, LTCG knocks your door, Taxed at ten percent, not steep, For gains from patience that run deep.",
    "STCG (Short-Term Capital Gains)": "Quick trades bring fast delight, But STCG taxes bite, Fifteen percent on what you make, For holding short, that’s the stake.",
    "Account Number": "Your money’s home has its ID, An account number for security, A string of digits, yours alone, To track your funds, your finance zone.",
    "IFSC Code": "To send or get, you’ll need the code, IFSC marks the banking road, A branch’s sign in letters and figures, For online moves, both small and bigger.",
    "MICR Code": "For cheques to clear at lightning speed, MICR code is what you need, Printed neat in magnetic ink, It helps the systems quickly think.",
    "Branch": "A bank’s own place, a public face, Your nearby branch is still the base, From cash to cards, from queries deep, It holds your trust, your money’s keep.",
    "Balance": "What’s left behind after you spend, Is your balance — your saving’s friend, A snapshot of your money’s stay, Ready to grow or drift away.",
    "Savings Account": "A place to store and earn a bit, Your savings account is a perfect fit, With interest slow but steady rise, It keeps your dreams within the skies.",
    "Current Account": "For business folk, fast and free, A current account’s the key, you see, No interest here, but limits none, It’s built for speed, for work that’s done.",
    "Fixed Deposit": "Lock it in for days or years, With fixed returns to calm your fears, No sudden dips, just steady pay, A fixed deposit leads the way.",
    "Recurring Deposit": "Small steps taken every month, A recurring deposit grows in strength, Disciplined and tightly set, It helps you reach each finance net.",
    "NRI Account": "Far from home, yet still in touch, NRI accounts offer much, To earn, to send, to wisely park, Your Indian link, a glowing spark.",
    "NEFT (National Electronic Funds Transfer)": "Bank to bank, from here to there, NEFT moves money with timely care, Batch by batch, it works all day, A safe and steady fund-transfer way.",
    "RTGS (Real-Time Gross Settlement)": "When big amounts must fly with speed, RTGS meets that very need, Real-time, direct, with no delay, It settles sums the same workday.",
    "IMPS (Immediate Payment Service)": "Quick and ready, day or night, IMPS makes your transfers right, Real-time cash from phone to bank, A tiny tap — a digital plank.",
    "UPI (Unified Payments Interface)": "Scan the code or type a name, UPI’s a seamless game, Linked with banks, yet apps you hold, To pay or earn, both young and old.",
    "Cheque": "A paper promise, signed with grace, A cheque moves money, face to face, Write the name, the sum, the date, And let the bank decide its fate.",
    "Demand Draft": "Prepaid and safe, a trusted note, Demand draft’s on paper wrote, Used when trust is yet to bloom, It clears like cheques but with more room.",
    "Debit Card": "Tap or swipe or simply scan, Your debit card’s the modern plan, It pulls from funds you truly own, And keeps your spending wisely shown.",
    "Credit Card": "Spend today, repay next time, With credit cards, you borrow prime, A plastic pass to credit’s door, With bills that come, and sometimes more.",
    "CVV (Card Verification Value)": "That little code behind the card, The CVV stands strong and guard, Three digits tight to keep you safe, From fraud and theft in online space.",
    "Net Banking": "Log in once, your world unfolds, Net banking’s where your account holds, Transfer, check, invest or pay, All done online — the modern way.",
    "Mobile Banking": "Bank in hand, you’re on the go, Mobile apps now run the show, Transfer funds or pay the bill, With just a tap, fulfill your will.",
    "OTP (One-Time Password)": "A secret code sent to your phone, Just once it lives, then it’s gone, OTP protects each online act, A digital shield — that’s a fact.",
    "Loan": "A loan is help when funds are tight, A borrowed sum to set things right, For homes, for dreams, or study's need, It plants today a future seed.",
    "EMI": "A little bit each month you pay, Your EMI clears debt day by day, A fixed amount, it brings you peace, Till loan and burden find release.",
    "Interest Rate": "The price you pay for borrowed cash, Or earn when savings start to stash, The interest rate is key to learn, It shows you how your rupees turn.",
    "Collateral": "If loans go bad and debts are high, Collateral helps the lender try, It’s pledged to guard the bank’s own fear, In case the borrower disappears.",
    "Credit Score": "A number small but mighty loud, It tells if lenders should feel proud, Of giving you a credit line, Or pausing till your records shine.",
    "Overdraft": "Need more cash than what’s in store? An overdraft can give you more, It lets you spend beyond your pile, But charges you in interest style.",
    "Statement": "A mirror of your banking trail, Each month your statement tells the tale, Of every rupee lost or earned, And lessons that your habits learned.",
    "Minimum Balance": "The least you need to keep things live, A minimum balance must survive, Fall below, and fines arrive, Like hidden bees inside a hive.",
    "Penalty Charges": "Break a rule or miss a date, And penalty charges seal your fate, A fee for slips, or late EMIs, They quickly climb and multiply.",
    "Service Charge": "The bank may charge for tasks it does, For SMS pings or banking fuzz, A service charge may greet your sheet, For extra perks that feel elite.",
    "KYC": "To guard against deceit and fraud, KYC stands firm and broad, With documents that prove you're real, It keeps the bank’s records ideal.",
    "PAN": "A ten-digit code that’s yours alone, PAN makes your money clearly known, For tax and banks, it's your ID, A passport to financial glee.",
    "Aadhaar": "India’s ID — unique and wide, Your Aadhaar lets you bank with pride, With name and face and fingerprint, It opens doors with instant hint.",
    "CIF Number": "Your CIF holds your banking soul, A digital ID in full control, It stores your data, links your name, Across accounts, it stays the same.",
    "PIN": "A four-digit wall that guards your card, The PIN keeps thieves and frauds barred, Without it, swipes go nowhere fast, It locks your money till you're asked.",
    "Phishing": "A fake email, a tricky link, Phishing waits where people blink, It asks for PINs or OTPs, And steals your funds with awful ease.",
    "Two-Factor Authentication": "One password’s fine, but two is best, To pass the fraudster’s sneaky test, A second step, like OTP, Adds double strength to security.",
    "SSL Encryption": "When sites show locks or turn to green, SSL guards the cyber scene, It scrambles data on its way, So hackers have no price to pay.",
    "Customer Due Diligence": "Banks must know just who you are, Not just your name or where you spar, Due diligence goes deep and wide, So shady moves don’t slip or hide.",
    "Enhanced Due Diligence": "If risk is high or stakes are tall, Enhanced checks rise to guard it all, More docs, more proof, a closer look, Beyond what standard forms once took.",
    "Simplified Due Diligence": "When risks are low and stakes are small, Simplified checks may cover all, No deep dive or endless forms, Just basic rules and standard norms.",
    "Politically Exposed Person": "If power rests in what you do, Or close connections follow too, You’re marked a PEP — with extra checks, To guard the flow from fraud’s effects.",
    "Beneficial Owner": "Behind each firm, there's one who gains, Though not the name that paper names, The real one pulling every string, Is called the beneficial king.",
    "KYC Documents": "A passport, Aadhaar, PAN, or bill, To prove your name and where you chill, These docs are keys to open doors, For banks, for trades, and many chores.",
    "e-KYC": "With just your Aadhaar, you can sign, Through e-KYC, the process is fine, No more papers, no long queues, Just digital checks with faster cues.",
    "Periodic KYC Update": "Though once you proved your ID true, KYC updates still wait for you, Every few years, a check comes back, To fill the gaps or data lack.",
    "KYC Norms": "These are the rules that guide the way, For how banks check and what to say, KYC norms are set with care, So risks are caught most anywhere.",
    "Risk-Based KYC": "Not all clients pose the same demand, Some need a quick, some a tighter hand, Risk-based KYC sorts them fast, From harmless trades to deals vast.",
    "KYC Registry": "A central store where records stay, The KYC registry lights the way, Banks can pull your verified file, To serve you fast and save the pile.",
    "Principal Amount": "The sum you start when loans begin, Before the rates and charges spin, The principal is what you owe, The base from which your payments grow.",
    "Reducing Balance Method": "Your interest shrinks with every pay, As principal drops day by day, You pay less over time, you see, It saves you more progressively.",
    "Flat Interest Rate": "The rate stays fixed, it does not bend, Though you repay from end to end, The interest’s charged on full amount, Not what remains in your account.",
    "Loan Tenure": "The loan’s full term — a year or ten, Decides how fast you’re free again, A longer span brings lower strain, But more the interest you sustain.",
    "Amortization Schedule": "A table neat, a plan so wise, It shows how debts reduce in size, With every EMI you send, This chart will show the journey’s end.",
    "Prepayment": "Pay more than what you owe each time, To end the loan before its prime, A step ahead, a weight released, With prepayment, your stress is ceased.",
    "Foreclosure": "One lump sum, and it’s goodbye debt, Your loan is closed, the score is set, Foreclosure clears the burden fast, And ends the dues that long could last.",
    "EMI Bounce": "If payment fails on due date night, An EMI bounce brings no delight, The bank may charge, your score may fall, And trouble comes with one missed call.",
    "NACH Mandate": "A mandate signed to smooth your pay, So EMIs debit right away, No checks, no taps, no monthly chase, NACH ensures your loan keeps pace.",
    "EMI in Arrears": "It’s most common, fair, and wide, the standard way banks often guide; you use the funds, then make it right, each month you pay for last month's light.",
  "EMI in Advance": "It’s rare, but some loans take this way where first you pay, then start your stay; just know the rules, weigh gains with cost to see if early pay is lost.",
  "Floating Interest Rate": "But when the market hikes its tone, your EMIs may groan and moan; it suits the brave who risk the game to win or lose in interest’s name.",
  "Fixed Interest Rate": "Though sometimes high when markets fall, its calm and peace outshine it all; for those who seek a stable ride, a fixed rate walks right by your side.",
  "EMI Calculator": "No guess or math that leaves you blind, it gives you peace and saves your mind; before you borrow, always see what your monthly due will be.",
  "PAN Card": "From buying land to earning high, a PAN Card stands like proof nearby; a tool for banks, for work, for law, it keeps your money life in awe.",
  "Form 49A": "For citizens who want their code, it starts your PAN’s official road; just fill and sign, attach a face, and PAN arrives to take its place.",
  "Form 49AA": "Investors, NRI, or guest, this form ensures their PAN’s addressed; with details true and rules that bind, it puts them on the Indian gridlined.",
  "Mandatory PAN Usage in Banking": "The rule is strict, the cause is fair, to track big moves and stop despair; no PAN, no pass to certain gates, it guards the vault and audit states.",
  "PAN-Aadhaar Linking": "The deadline nears, the rule is stern; without this link, you’ll feel the burn; so tie them fast, avoid the block and keep your tax life on the clock.",
  "PAN Validation": "For KYC, for tax, for deal, this step ensures your data's real; PAN validation saves the day from scams that lead your funds astray.",
  "PAN for Minor": "It builds a trail, a paper start for when they join the financial chart; their future funds and taxes wise begin beneath this PAN disguise.",
  "PAN for Non-Individual Entities": "They file returns and pay their share with PAN to prove they’re playing fair; a tax ID for every kind to keep their books and laws aligned.",
  "PAN Exemptions": "But mostly all must have their code to track their cash and tax abode; so know if you are truly free or need PAN for your money spree.",
  "PAN Quoting for TDS": "Without it, TDS will stay withheld and lost in tax array; so quote your PAN when money flows to clear the path your income grows.",
  "PAN in KYC": "Banks and brokers want this proof before you sign or use their roof; PAN in KYC makes all things smooth and lawful for your money move.",
  "PAN and Form 60": "When PAN is missing or delayed, Form 60 stands not dismayed; it lets you state you lack the ID but still comply with law’s decree.",
  "PAN Status Tracking": "You wait and check with hopeful heart, the PAN’s status plays its part; online tools keep you informed so you know when card is formed.",
  "Duplicate PAN Card": "Lost your card or it got torn? Duplicate PAN can be born; just apply and wait again to get your card to ease your pain.",
  "Bank Locker": "To keep your valuables in store, bank lockers offer safety’s core; secured space with bank’s strong guard, your treasures safe and unmarred.",
  "Locker Agreement": "Renting lockers, you must sign a pact that sets the rules and line; it binds your rights and bank’s care for safekeeping your valuables rare.",
  "Locker Rent": "Each year you pay a fee to keep your locker safe in bank’s deep; a small cost for peace of mind, that lets your valuables unwind.",
  "Nomination Facility": "You name the one who will receive your locker’s wealth if you deceive; a trusted person to inherit all your stored valuables’ call.",
  "Locker Key": "The key’s the secret to the box, without it, doors remain locked rocks; keep it safe and never lose to keep your things and bank’s good news.",
  "Joint Locker": "Shared locker with your friend or kin lets more than one come safely in; both hold the power to unlock and guard the vault’s precious stock.",
  "Custodian Key": "Sometimes a bank holds the key when owners can’t always be; custodian keeps the access tight for valuables day and night.",
  "Safe Custody": "Banks keep deeds and gold with care in safe custody’s guarded lair; you entrust your valuables there with security beyond compare.",
  "Locker Access Register": "Each time you open or you close, the register logs your visits close; a record kept for trust and law to track who touched the locker’s draw.",
  "Surrender of Locker": "If you leave, the locker’s freed, return the key, fulfill the deed; end your contract, pay your dues, and clear the bank’s safe-holding blues.",
  "Locker Breaking": "When keys are lost and access gone, banks may break the locker on; with your presence or legal nod, to open safe your prized trod.",
  "Security Deposit": "A deposit holds your safety bond to rent the locker and respond; refundable when you depart, it guards the bank and guards your heart.",
  "Liability of Bank": "Bank must guard with care and skill, but some losses come by will; liability kicks in when they fail to keep your valuables safe without ail.",
  "RBI Locker Guidelines": "RBI sets the rules and rates to govern locker rental fates; they protect customers’ rights with clear instructions day and nights.",
  "Indemnity Bond": "A bond that shields from claims or losses, signed with bank in honest aims; indemnity bonds keep trust intact when something goes off track.",
  "Credit Report": "Your credit report shows your loan and cards, your history known; banks check this before they lend to know if you can repay in end.",
  "Debit Card": "Spend your cash with plastic swipe; debit card’s funds are ripe; no credit given, just your own, money flows from bank’s own throne.",
  "Credit Card": "Buy today, pay next month due; credit card lets debts accrue; spend with care, pay on time, or fees and interest will climb.",
  "Mortgage": "A loan secured by home or land, with monthly payments planned; mortgage helps you buy and own your house or plot or even zone.",
  "APR (Annual Percentage Rate)": "The yearly cost you truly pay, includes fees and interest sway; APR tells you what loans cost, so choices won’t be sadly lost.",
  "Stock": "Owning stocks means owning part of a company’s beating heart; prices rise and fall each day, gains and losses come your way."
};


const wordList = document.querySelectorAll('#wordList li');
const descriptionBox = document.getElementById('descriptionBox');
const searchInput = document.getElementById('searchInput');

function showDescription(word) {
    if (descriptions[word]) {
        descriptionBox.innerHTML = `<h3>${word}</h3><br><p>${descriptions[word]}</p><br><p>${example1[word]}</p><br><p>${eg[word]}</p>`;
    } else {
        descriptionBox.innerHTML = "<p>No description available.</p>";
    }
}

wordList.forEach(item => {
    item.addEventListener('click', function () {
        wordList.forEach(li => li.classList.remove("active"));
        this.classList.add("active");
        const word = this.dataset.word;
        showDescription(word);
    });
});

searchInput.addEventListener('input', function () {
    const filter = this.value.toLowerCase();
    let firstMatch = null;

    wordList.forEach(item => {
        const word = item.textContent.toLowerCase();
        if (word.includes(filter)) {
            item.style.display = '';
            if (!firstMatch) firstMatch = item.dataset.word;
        } else {
            item.style.display = 'none';
        }
        item.classList.remove("active");
    });

    if (firstMatch) {
        showDescription(firstMatch);
        const activeItem = [...wordList].find(item => item.dataset.word === firstMatch);
        activeItem?.classList.add("active");
    } else {
        descriptionBox.innerHTML = "<p>No matching word found.</p>";
    }
});